### ISSUE TITLE
We still need to connect eggnog website when run_mantis?

### ISSUE THREAD

**Issue by xiekunwhy** [PedroMTQ/mantis#16]
Hi @PedroMTQ ,

We still need to connect eggnog website when run_mantis ?

cat nohup.out
Executing command:
 /state/partition1/WORK/Bio/Project/xiek/software/mantis/ run_mantis -t /state/partition1/WORK/Bio/Project/xiek/pipe/divtime/bamboo/ref/annot/bbu.blast/all.fa -o bamboo -mc /state/partition1/WORK/Bio/Project/xiek/pipe/annot/mantis/MANTIS.config
------------------------------------------
  Setting up Mantis!
------------------------------------------
  Reading config file and setting up paths
Using custom MANTIS.config: /state/partition1/WORK/Bio/Project/xiek/pipe/annot/mantis/MANTIS.config
User configuration:
------------------------------------------
Output folder:			bamboo/
Mantis config:			/state/partition1/WORK/Bio/Project/xiek/pipe/annot/mantis/MANTIS.config
Target path:			/state/partition1/WORK/Bio/Project/xiek/pipe/divtime/bamboo/ref/annot/bbu.blast/all.fa
E-value threshold:		0.001
Overlap value:			0.1
HMMER threads:			1
Algorithm:			dfs
------------------------------------------
  This MANTIS process started running at 2021-05-22 10:06:52
Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6773cb12e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='eggnog5.embl.de', port=80): Max retries exceeded with url: /download/latest/per_tax_level/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6773cb12e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/__main__.py", line 150, in <module>
    run_mantis(target_path=target_path,
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS.py", line 70, in run_mantis
    mantis.run_mantis()
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/utils.py", line 537, in wrapper
    res = f(self, *args, **kwargs)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS.py", line 455, in run_mantis
    self.check_installation(verbose=False)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS_Assembler.py", line 520, in check_installation
    tax_hmms = self.get_taxon_hmms(db='NOG', folder=True)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS_Assembler.py", line 646, in get_taxon_hmms
    taxon_ids = self.get_hmm_taxon_ids(db)
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS_Assembler.py", line 629, in get_hmm_taxon_ids
    available_taxon_ids = self.get_taxon_ids_NOGT()
  File "/state/partition1/WORK/Bio/Project/xiek/software/mantis/source/MANTIS_DB.py", line 1017, in get_taxon_ids_NOGT
    req = requests.get(url)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Bio/User/kxie/software/anaconda3/envs/mantis/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='eggnog5.embl.de', port=80): Max retries exceeded with url: /download/latest/per_tax_level/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6773cb12e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Cores allocated: 32
Memory allocated: 119.78
Workers per core: 1

Best,
Kun

**Comment by PedroMTQ** [comment]
Hello,
Indeed, during the installation check, Mantis checks eggNOG's webpage to see if all HMMs are available, I've now changed the implementation so that if no internet connection is done, then we simply look into the directory.
This should solve your problem given your current connection limitations.
Please update your local repo.

Regards,
Pedro
