### ISSUE TITLE
Crash in setup_databases download_uniprot_reference

### ISSUE THREAD

**Issue by IanReid** [PedroMTQ/mantis#2]
I have installed mantis on a compute server running Ubuntu 18.04.1 LTS using the command 'git clone https://github.com/PedroMTQ/mantis.git' . The git HEAD of the installed version is d983816258b6137f5dc27a94977ef0841414b2e4
I have tried three times to run mantis setup_databases. In each attempt the program has aborted before completion with the error message:
Traceback (most recent call last):
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./mantis/source/MANTIS_DB.py", line 135, in worker_setup_databases
    self.run_download_and_unzip(database,force_download,taxon_id,stdout_path)
  File "./mantis/source/MANTIS_DB.py", line 162, in run_download_and_unzip
    elif database=='uniprot_nlp':    self.download_uniprot_reference(force_download=force_download,stdout_file=stdout_file)
  File "./mantis/source/MANTIS_DB.py", line 233, in download_uniprot_reference
    uncompress_archive(source_filepath=self.mantis_paths['uniprot_nlp'] + file, stdout_file=stdout_file, remove_source=False)
  File "./mantis/source/utils.py", line 431, in uncompress_archive
    gunzip(source_filepath=source_filepath,dest_filepath=extract_path,block_size=block_size,remove_source=remove_source,stdout_file=stdout_file)
  File "./mantis/source/utils.py", line 448, in gunzip
    block = s_file.read(block_size)
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

**Comment by PedroMTQ** [comment]
That's strange, I'm looking into this right now and will let you know as soon as possible what's going on.

**Comment by PedroMTQ** [comment]
@IanReid somehow some of the resources were corrupted when I copied them from the internal repository to the external (github) repository! I replaced these files (go and uniprot resources) and reran the setup on my local machine and everything ran smoothly.
Could you please clone the repository again and try to run setup_databases again?

**Comment by IanReid** [comment]
Thanks for the quick response!
I have pulled the updates from the repository:
Resources/Gene_Ontology/go.obo.pickle_dict         | Bin 133 -> 7936757 bytes
 Resources/Gene_Ontology/go.obo.pickle_syns         | Bin 132 -> 6650539 bytes
 Resources/Gene_Ontology/go.obo.pickle_terms        | Bin 131 -> 173478 bytes
 .../Uniprot/uniprot-filtered-reviewed_yes.tab.gz   | Bin 133 -> 10223009 bytes
 ...prot-filtered-reviewed_yes.tab_n_grams_1.pickle | Bin 132 -> 4138452 bytes
 5 files changed, 0 insertions(+), 0 deletions(-)

Now I am rerunning setup_databases; so far so good. It is still verifying the hmm and annotations files that were already downloaded. I will report back when the setup ends.

**Comment by IanReid** [comment]
The setup_databases progressed through the hmm download and splitting phases with apparent success, but then threw another error in extracting NOG metadata. 
Error message: 
#  Will now extract metadata from NOG!
Unpacking  /mnt/data/disk/opt/bioinformatics/mantis/Resources/NOG_sql.tar.gz
Traceback (most recent call last):
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/shutil.py", line 1155, in _unpack_tarfile
    tarobj = tarfile.open(filename)
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/tarfile.py", line 1606, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mantis/__main__.py", line 114, in <module>
    setup_databases(force_download=force_download,chunk_size=chunk_size,mantis_config=mantis_config)
  File "mantis/source/MANTIS_Assembler.py", line 28, in setup_databases
    mantis.setup_databases(force_download)
  File "mantis/source/utils.py", line 417, in wrapper
    res = f(self,*args, **kwargs)
  File "mantis/source/MANTIS_DB.py", line 57, in setup_databases
    self.prepare_queue_extract_metadata()
  File "mantis/source/MANTIS_DB.py", line 97, in prepare_queue_extract_metadata
    self.unpack_NOG_sql(stdout_file=stdout_file)
  File "mantis/source/MANTIS_DB.py", line 430, in unpack_NOG_sql
    uncompress_archive(source_filepath=NOG_sql_path,extract_path=resources_path,stdout_file=stdout_file,remove_source=False)
  File "mantis/source/utils.py", line 428, in uncompress_archive
    unpack_archive(source_file=source_filepath, extract_dir=extract_path, remove_source=remove_source, stdout_file=None)
  File "mantis/source/utils.py", line 458, in unpack_archive
    shutil.unpack_archive(source_file,extract_dir=extract_dir)
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/shutil.py", line 1227, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/home/ian_reid/conda/envs/mantis_env/lib/python3.8/shutil.py", line 1157, in _unpack_tarfile
    raise ReadError(
shutil.ReadError: /mnt/data/disk/opt/bioinformatics/mantis/Resources/NOG_sql.tar.gz is not a compressed or uncompressed tar file

The mantis/Resources/NOG_sql.tar.gz is only 134 bytes.

**Comment by IanReid** [comment]
The 134-byte NOG_sql.tar.gz file appears to be a failed download.
I have downloaded the 167.9 M file from the repository and restarted setup_databases.

**Comment by PedroMTQ** [comment]
Hello again, apparently `git clone` is not cloning large files added with git lfs! I reproduced the error in my laptop too and figured out the solution would be to either manually download the file (as you did) or to run:
``git lfs install``
``git lfs clone git@github.com:PedroMTQ/mantis.git``

Sorry for the inconvenience, I wasn't aware of this git behavior.
I'll make sure add this to the readme!

The setup should now run, please let me know if you have any issues!

**Comment by IanReid** [comment]
Both setup_databases and check_installation have now completed successfully, so I will close this issue.
Thanks for your help.
