### ISSUE TITLE
Database building UnboundLocalError: local variable 'main_tile' referenced before assignment

### ISSUE THREAD

**Issue by alxsimon** [PedroMTQ/mantis#23]
Hi, when building the database there is this error during the process (`python mantis setup_databases`).
It does not kill the job as this is still running, but it seems it will have an impact.

```
Traceback (most recent call last):                                                           
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap        
    self.run()                                                                               
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run               
    self._target(*self._args, **self._kwargs)                                                
  File "mantis/source/MANTIS_DB.py", line 183, in worker_setup_databases                     
    self.download_database(database, force_download, taxon_id, stdout_path)
  File "mantis/source/MANTIS_DB.py", line 218, in download_database
    elif database == 'kofam':       self.download_kofam(force_download=force_download, stdout_file=stdout_file)
  File "mantis/source/MANTIS_DB.py", line 546, in download_kofam
    self.compile_kofam_metadata()                                                            
  File "mantis/source/MANTIS_DB.py", line 412, in compile_kofam_metadata
    self.get_link_kofam_ko_to_pathway(metadata_to_write)                                     
  File "mantis/source/MANTIS_DB.py", line 462, in get_link_kofam_ko_to_pathway
    map_description = self.get_kofam_pathway_description()                                   
  File "mantis/source/MANTIS_DB.py", line 513, in get_kofam_pathway_description
    res[kegg_map] = {'description': description, 'parent': sub_title, 'grand_parent': main_tile}
UnboundLocalError: local variable 'main_tile' referenced before assignment
```

**Comment by PedroMTQ** [comment]
Hi @alxsimon ,

KEGG recently changed their website so KEGG map lineage descriptions could no longer be scraped as before. Since they may change this again in the future I have removed this particular feature of the kofam metadata generation.

I've updated the repo with this fix (and a few other minor changes), please let me know if you run into any issues!

Regards,
Pedro

**Comment by alxsimon** [comment]
Great, thanks for the quick fix Pedro!
Best regards,
Alexis
