### ISSUE TITLE
Pfam issue download

### ISSUE THREAD

**Issue by Lcornet** [PedroMTQ/mantis#24]
I have an error during the database setup:

Cloning into '/media/vol2/home/galaxy/mantis/Resources/UniFunc'...
Process Process-3:
Traceback (most recent call last):
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "mantis/source/MANTIS_DB.py", line 178, in worker_setup_databases
    self.download_database(database, force_download, taxon_id, stdout_path)
  File "mantis/source/MANTIS_DB.py", line 212, in download_database
    elif database == 'pfam':        self.download_pfam(force_download=force_download, stdout_file=stdout_file)
  File "mantis/source/MANTIS_DB.py", line 390, in download_pfam
    download_file(url, output_folder=self.mantis_paths['pfam'], stdout_file=stdout_file)
  File "mantis/source/utils.py", line 669, in download_file
    if os.stat(file_path).st_size == target_size: return
FileNotFoundError: [Errno 2] No such file or directory: '/media/vol2/home/galaxy/mantis/References/pfam/Pfam-A.hmm.gz'

Could you help me to solve this ?

**Comment by PedroMTQ** [comment]
Hello @Lcornet 
That is a strange bug, it might be that you were not able to download the Pfam-A.hmm.gz file.
I have added a quick fix to check whether the file exists, hopefully when you launch it again you will manage to download the file correctly.

Let me know if you run into any issues.
Regards,
Pedro

**Comment by Lcornet** [comment]
It works for pfams now, thanks

**Comment by Lcornet** [comment]
I have a new error:

Traceback (most recent call last):
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.uniprot.org', port=443): Max retries exceeded with url: /uploadlists/ (Caused by SSLError(SSLZeroReturnE
rror(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "mantis/source/MANTIS_DB.py", line 178, in worker_setup_databases
    self.download_database(database, force_download, taxon_id, stdout_path)
  File "mantis/source/MANTIS_DB.py", line 215, in download_database
    elif database == 'tcdb':        self.download_tcdb(force_download=force_download, stdout_file=stdout_file)
  File "mantis/source/MANTIS_DB.py", line 829, in download_tcdb
    self.compile_tcdb_metadata()
  File "mantis/source/MANTIS_DB.py", line 790, in compile_tcdb_metadata
    seqs_found=self.remove_bad_entries(list(all_seqs.keys()))
  File "mantis/source/MANTIS_DB.py", line 760, in remove_bad_entries
    response=requests.post(url, data=post_obj,headers=headers)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/media/vol2/home/galaxy/miniconda/envs/mantis_env/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.uniprot.org', port=443): Max retries exceeded with url: /uploadlists/ (Caused by SSLError(SSLZeroReturnError
(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1123)')))

**Comment by Lcornet** [comment]
How can I fix this ?

**Comment by PedroMTQ** [comment]
Hello @Lcornet 
It seems you have some connection constraints in your current system, are there any restrictions in place?
The error you show is not related to Mantis, but to requests, a package that can be used to access websites.
Could you perhaps try to run this small snippet to check whether you can properly use requests?
```
def test():
    import requests
    c = 0
    url = 'https://www.uniprot.org/uploadlists/'
    post_obj={'query':'P13368 P20806 ZP_02735776','format':'tab','from':'ACC','to':'ACC'}
    headers = {'Content_Type': 'form-data'}
    response = requests.post(url, data=post_obj, headers=headers)
    while response.status_code != 200 and c<=10:
        response = requests.post(url, data=post_obj, headers=headers)
        c += 1
    response_text = response.text
    print(response_text)
```
I have tested it locally and it runs fine on my system, you should get a response like this:
```
From	To
P13368	P13368
P20806	P20806
```

Regarding your actual issues with requests, I have quickly googled and found others with similar issues:
https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

Perhaps you could try some of the fixes there? Might also be some issues with packages in your system, I'm honestly unsure since I can't replicate the issue locally.

Regards,
Pedro

**Comment by Lcornet** [comment]
I was on a centos7 and it's difficult to update thing.

So I try to install it on our centos8 cluster and I got this error:

Cloning into '/scratch/users/l/c/lcornet/mantis/Resources/UniFunc'...
fatal: unable to access 'https://github.com/PedroMTQ/UniFunc.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "mantis/source/MANTIS_NLP.py", line 9, in <module>
    from Resources.UniFunc.source import UniFunc
ModuleNotFoundError: No module named 'Resources.UniFunc.source'

Sorry to bother you ...

**Comment by PedroMTQ** [comment]
Hi @Lcornet 
This again seems to be some issue with your configuration, this time regarding git...
You could try to manually clone the repo, just place the UniFunc folder in ```Mantis/Resources/```

**Comment by Lcornet** [comment]
Hi Pedro,

I solved the problems of git configuration and pip dependencies.
I run the setup database but I still have a problem. Mantis run but without writing anything.  
```
Unpacking /media/vol2/home/galaxy/mantis/References/NOG/2/2_hmms.tar.gz to /media/vol2/home/galaxy/mantis/References/NOG/2/profiles
Unpacking /media/vol2/home/galaxy/mantis/References/NOG/32066/32066_hmms.tar.gz to /media/vol2/home/galaxy/mantis/References/NOG/32066/profiles
Unpacking /media/vol2/home/galaxy/mantis/References/NOG/85005/85005_hmms.tar.gz to /media/vol2/home/galaxy/mantis/References/NOG/85005/profiles
Unpacking /media/vol2/home/galaxy/mantis/References/NOG/40117/40117_hmms.tar.gz to /media/vol2/home/galaxy/mantis/References/NOG/40117/profiles
```
This is the last message that mantis gave me since the last four hours. Is it normal ?

Thanks

**Comment by PedroMTQ** [comment]
Hello @Lcornet ,
This is the output in the Mantis.out file correct?
What do you mean that mantis is running without writing anything?  eggNOG download and unpacking does take a while since it's more than 1 TB of data. You could maybe check whether any of the reference files are being changed:
``` ls -lh /media/vol2/home/galaxy/mantis/References/NOG/*/*```

The higher taxons are especially comprehensive (e.g., taxon 2 has 19GB of HMMs)

Regards,
Pedro

**Comment by Lcornet** [comment]
This is the output of setup_databases/Mantis.out:

#  Downloading and unzipping TCDB sequences
Not downloading from http://www.tcdb.org/public/tcdb since file was already found!
/media/vol2/home/galaxy/mantis/Resources/Diamond/diamond: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /media/vol2/home/galaxy/mantis/Resources/Diamond/diamond)
/media/vol2/home/galaxy/mantis/Resources/Diamond/diamond: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /media/vol2/home/galaxy/mantis/Resources/Diamond/diamond)
Finished downloading tcdb
Setup failed on tcdb None
#  Downloading and unzipping TCDB sequences
Not downloading from http://www.tcdb.org/public/tcdb since file was already found!
/media/vol2/home/galaxy/mantis/Resources/Diamond/diamond: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /media/vol2/home/galaxy/mantis/Resources/Diamond/diamond)
/media/vol2/home/galaxy/mantis/Resources/Diamond/diamond: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /media/vol2/home/galaxy/mantis/Resources/Diamond/diamond)
Finished downloading tcdb
Setup failed on tcdb None
#  Downloading and unzipping TCDB sequences
Not downloading from http://www.tcdb.org/public/tcdb since file was already found!
/media/vol2/home/galaxy/mantis/Resources/Diamond/diamond: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /media/vol2/home/galaxy/mantis/Resources/Diamond/diamond)
/media/vol2/home/galaxy/mantis/Resources/Diamond/diamond: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /media/vol2/home/galaxy/mantis/Resources/Diamond/diamond)
Finished downloading tcdb
Setup failed on tcdb None
#  Downloading and unzipping TCDB sequences
Not downloading from http://www.tcdb.org/public/tcdb since file was already found!


 ls -lrt /media/vol2/home/galaxy/mantis/References/NOG/*/*

-rw-r--r-- 1 galaxy 11443095516 Jun 18 19:49 /media/vol2/home/galaxy/mantis/References/NOG/2759/2759_merged.hmm.h3m
-rw-r--r-- 1 galaxy     7411722 Jun 18 19:49 /media/vol2/home/galaxy/mantis/References/NOG/2759/2759_merged.hmm.h3i
-rw-r--r-- 1 galaxy  4460360278 Jun 18 19:49 /media/vol2/home/galaxy/mantis/References/NOG/2759/2759_merged.hmm.h3f
-rw-r--r-- 1 galaxy 13429416941 Jun 18 19:49 /media/vol2/home/galaxy/mantis/References/NOG/2759/2759_merged.hmm.h3p

**Comment by Lcornet** [comment]
I should be able to solve  /lib64/libc.so.6 problem, is it needed for the setup_db process ?

Thanks,
Luc

**Comment by PedroMTQ** [comment]
Hey @Lcornet 

Yes, you'd need to solve the dependency issue in order to proceed with the setup. I think Diamond requires GLIBC_2.14 in order to run, since we are using Diamond to compile the TCDB databases, the Mantis' setup_databases process is failing on that step.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Has this been solved? Will close issue soon

**Comment by Lcornet** [comment]
Yes It has been solved. Three different problem. The main one, about GLIBC_2.14, was solved by changing the OS. CentOS 7 was too old for the compiled version of Diamond. It works on Cent OS 8.
