### ISSUE TITLE
expected string or bytes-like object

### ISSUE THREAD

**Issue by Lcornet** [PedroMTQ/mantis#26]
Dear Pedro

I have an error while running mantis. 
This happens when a run mantis in a slurm job. From the terminal, it works but not in a slurm job.

Executing command:
 mantis run_mantis -t GC_00001818_OG.fasta -o test
------------------------------------------
#  Setting up Mantis!
------------------------------------------
#  Reading config file and setting up paths
User configuration:
------------------------------------------
Output folder:                  test/
Target path:                    GC_00001818_OG.fasta
E-value threshold:              0.001
Overlap value:                  0.1
HMMER threads:                  1
Algorithm:                      dfs
------------------------------------------
#  This MANTIS process started running at 2021-06-29 21:06:21
Traceback (most recent call last):
  File "/scratch/ulg/bioec/lcornet/miniconda/envs/mantis_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/ulg/bioec/lcornet/miniconda/envs/mantis_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mantis/__main__.py", line 150, in <module>
    run_mantis(target_path=target_path,
  File "mantis/source/MANTIS.py", line 78, in run_mantis
    mantis.run_mantis()
  File "mantis/source/utils.py", line 550, in wrapper
    res = f(self, *args, **kwargs)
  File "mantis/source/MANTIS.py", line 463, in run_mantis
    self.check_installation(verbose=False)
  File "mantis/source/MANTIS_Assembler.py", line 513, in check_installation
    tax_hmms = self.get_taxon_refs(db='NOG', folder=True)
  File "mantis/source/MANTIS_Assembler.py", line 658, in get_taxon_refs
    taxon_ids=self.get_ref_taxon_ids(db)
  File "mantis/source/MANTIS_Assembler.py", line 630, in get_ref_taxon_ids
    available_taxon_ids = self.get_taxon_ids_eggNOG()
  File "mantis/source/MANTIS_DB.py", line 1016, in get_taxon_ids_eggNOG
    taxons_search = re.findall('href="\d+/"', webpage)
  File "/scratch/ulg/bioec/lcornet/miniconda/envs/mantis_env/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
Cores allocated: 10
Memory allocated: 1998.68
Workers per core: 1

Can you help me with this problem ? Is there any connection on internet when running mantis (not allowed from of computing node) ?

Thanks
Luc

**Comment by PedroMTQ** [comment]
Hello @Lcornet 

Yes, usually Mantis checks which eggNOG HMMs are available in the eggNOG webpage. But no matter, now it will check the webpage, and , if not connection is established, it will only check for the HMMs locally.
I've updated the repo with this small update so please update your copy of Mantis as well.

Let me know if you run into any issues.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Closing since there have been no updates from OP.
