### ISSUE TITLE
How to run custom database

### ISSUE THREAD

**Issue by iquasere** [PedroMTQ/mantis#38]
I have a local copy of uniprot in DMND format at ```path/to/uniprot.dmnd```. I'm trying to get mantis to annotate with it using this config
```
#This file is meant to be edited in your own distribution of MANTIS

#######DEFAULT PATHS#######
#You can add custom paths here, otherwise they will be set to default values
#resources_folder=
#default_ref_folder=
#####<custom_ref_folder> defines the folder where Mantis will look for MULTIPLE custom HMMs or DMND. Each HMM should be contained within a folder, such that the path will look something like this: /path/to/custom_ref_folder/custom1/custom1.hmm
#custom_ref_folder=
nog_ref=dmnd # dmnd or hmm
#nog_ref_folder=
#pfam_ref_folder=
#kofam_ref_folder=
#ncbi_ref_folder=
#tcdb_ref_folder=
#nog_tax=NCBI_ID

#####Make sure the  names of the weights correspond to the path of the hmms
#####example: <NOGT>_ref_folder should be <NOGT>_weight
#####example: custom_ref=path/to/customHMM.hmm should be customHMM_weight
nog_weight=0.8
pfam_weight=0.9


#######CUSTOM REFERENCES#######
#####<custom_ref> defines the folder or file where Mantis will look for a SINGLE custom reference (HMM or DMND). The path will look something like this: /path/to/custom1/custom1.hmm or /path/to/custom1/
custom_ref=path/to/uniprot.dmnd
#custom_ref=path/to/hmm/custom2.dmnd
#to set the weight, simply add a line with the hmm file name followed by _weight , like so:
path/to/uniprot_weight=0.5
```
Running ```python mantis run_mantis -i ann_paper/genes_trimmed.fasta -o ann_paper/mantis_genomes -c 15``` gets me
```
------------------------------------------
#  Setting up Mantis!
------------------------------------------
#  Reading config file and setting up paths
User configuration:
------------------------------------------
Output folder:                  ann_paper/mantis_genomes_2022-01-05T105119_hex_32ac65a9e1/
Target path:                    ann_paper/genes_trimmed.fasta
E-value threshold:              0.001
Overlap value:                  0.1
User cores:                     15
HMMER threads:                  1
Algorithm:                      dfs
------------------------------------------
#  This MANTIS process started running at 2022-01-05 10:51:19
Cores allocated: 15
Memory allocated: 115.29
Workers per core: 1
Traceback (most recent call last):
  File "/home/jsequeira/anaconda3/envs/mantis_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jsequeira/anaconda3/envs/mantis_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mantis/__main__.py", line 166, in <module>
    run_mantis(input_path=input_path,
  File "mantis/source/MANTIS.py", line 94, in run_mantis
    mantis.run_mantis()
  File "mantis/source/utils.py", line 587, in wrapper
    res = f(self, *args, **kwargs)
  File "mantis/source/MANTIS.py", line 496, in run_mantis
    self.check_installation(verbose=True)
  File "mantis/source/Assembler.py", line 523, in check_installation
    self.compile_sql_metadata()
  File "mantis/source/Assembler.py", line 496, in compile_sql_metadata
    cursor = Metadata_SQLITE_Connector(metadata_file)
  File "mantis/source/Metadata_SQLITE_Connector.py", line 12, in __init__
    kill_switch(MissingMetadataFile)
NameError: name 'MissingMetadataFile' is not defined
```

**Comment by PedroMTQ** [comment]
Hello @iquasere,

Could you try using the latest version? I believe this has been fixed.
I also just fixed a few other issues I found.

Btw, when you set the weight, it should be `uniprot_weight=0.5` and not `path/to/uniprot_weight=0.5`

Anyway, sorry for the inconvenience.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Hello @iquasere ,

I believe this has been fixed, I will close the issue, please feel free to reopen if you encounter this issue with the current version.

Regards,
Pedro
