### ISSUE TITLE
binny enhancements

### ISSUE THREAD

**Issue by PedroMTQ** [PedroMTQ/mantis#41]
- notify if metadata.tsv is not available but dont fail check
- remove download of taxonomy dbs

**Comment by PedroMTQ** [comment]
add relative paths to all paths

**Comment by PedroMTQ** [comment]
fix typo when not using taxonomy

**Comment by ohickl** [comment]
Metadata should handle empty tsv
```
Creating SQL database /scratch/users/ohickl/binning/tools/binny_devel/database/hmms/checkm_pf/metadata.db
Traceback (most recent call last):
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/bin/mantis", line 11, in <module>
    sys.exit(main())
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/__main__.py", line 144, in main
    run_mantis(input_path=input_path,
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/MANTIS.py", line 93, in run_mantis
    mantis.run_mantis()
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/utils.py", line 588, in wrapper
    res = f(self, *args, **kwargs)
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/MANTIS.py", line 476, in run_mantis
    self.check_installation(verbose=True)
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/Assembler.py", line 495, in check_installation
    self.compile_sql_metadata()
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/Assembler.py", line 467, in compile_sql_metadata
    cursor = Metadata_SQLITE_Connector(metadata_file)
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/Metadata_SQLITE_Connector.py", line 18, in __init__
    self.create_sql_table()
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/Metadata_SQLITE_Connector.py", line 133, in create_sql_table
    self.store_metadata()
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/Metadata_SQLITE_Connector.py", line 155, in store_metadata
    self.cursor.executemany(insert_command, table_chunk)
sqlite3.OperationalError: near ")": syntax error
```

**Comment by ohickl** [comment]
```
Metadata file missing: /scratch/users/ohickl/binning/tools/binny_devel/database/hmms/checkm_tf/metadata.tsv
ESC[32mCython correctly compiled!ESC[0m
ESC[33mChecking extra filesESC[0m
ESC[32mPassed installation check on: /scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/Resources/essential_genesESC[0m
ESC[32mPassed installation check on: /scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/Resources/NCBI/gc.prt.dmpESC[0m
ESC[33mChecking references installationESC[0m
ESC[31mFailed installation check on [files missing]: /scratch/users/ohickl/binning/tools/binny_devel/database/hmms/checkm_tf/
.h3m; .h3f; .h3pESC[0m
ESC[32mPassed installation check on: /scratch/users/ohickl/binning/tools/binny_devel/database/hmms/checkm_pf/ESC[0m
ESC[31mInstallation check failed on:
/scratch/users/ohickl/binning/tools/binny_devel/database/hmms/checkm_tf/
ESC[0m
ESC[33m------------------------------------------ESC[0m
ESC[31m--------INSTALLATION CHECK FAILED!--------ESC[0m
ESC[33m------------------------------------------ESC[0m
Traceback (most recent call last):
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/bin/mantis", line 11, in <module>
    sys.exit(main())
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/__main__.py", line 144, in main
    run_mantis(input_path=input_path,
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/MANTIS.py", line 93, in run_mantis
    mantis.run_mantis()
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/utils.py", line 588, in wrapper
    res = f(self, *args, **kwargs)
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/MANTIS.py", line 476, in run_mantis
    self.check_installation(verbose=True)
  File "/scratch/users/ohickl/binning/tools/binny_devel/conda/c0f804ea68e7de9036a9c6464c13d7d5/lib/python3.9/site-packages/mantis/Assembler.py", line 569, in check_installation
    raise InstallationCheckNotPassed
mantis.Exceptions.InstallationCheckNotPassed: Installation check not passed! Make sure you've setup the databases
```
