### ISSUE TITLE
mantis setup issue

### ISSUE THREAD

**Issue by AAwan2** [PedroMTQ/mantis#47]
Hi,

I installed mantis using conda install which went fine:
conda create -p /tools/Miniconda3/envs/mantis_annotate -c conda-forge -c bioconda mantis_pfa

However, when I run:
mantis setup

I get the following error:
Traceback (most recent call last):
  File "/tools/Miniconda3/envs/mantis_annotate/bin/mantis", line 7, in <module>
    from mantis.__main__ import main
  File "/tools/Miniconda3/envs/mantis_annotate/lib/python3.10/site-packages/mantis/__main__.py", line 7, in <module>
    from mantis.mantis import run_mantis, run_mantis_test, print_citation_mantis, print_version
  File "/tools/Miniconda3/envs/mantis_annotate/lib/python3.10/site-packages/mantis/mantis.py", line 110, in <module>
    class MANTIS(Multiprocessing):
NameError: name 'Multiprocessing' is not defined

I am unsure what the issue is here and would appreciate some help! Thank you!

**Comment by ningyuanlu** [comment]
I'm having the same problem.
Cloning into '/data/home/luningyuan/anaconda3/lib/python3.11/site-packages/Resources/UniFunc'...
fatal: unable to access 'https://github.com/PedroMTQ/UniFunc.git/': Empty reply from server
Traceback (most recent call last):
  File "/data/home/luningyuan/anaconda3/bin/mantis", line 7, in <module>
    from mantis.__main__ import main
  File "/data/home/luningyuan/anaconda3/lib/python3.11/site-packages/mantis/__main__.py", line 7, in <module>
    from mantis.mantis import run_mantis, run_mantis_test, print_citation_mantis, print_version
  File "/data/home/luningyuan/anaconda3/lib/python3.11/site-packages/mantis/mantis.py", line 110, in <module>
    class MANTIS(Multiprocessing):
                 ^^^^^^^^^^^^^^^
NameError: name 'Multiprocessing' is not defined
