### ISSUE TITLE
Mantis database checks failed

### ISSUE THREAD

**Issue by Rohit-Satyam** [PedroMTQ/mantis#48]
I installed Mantis as adviced and was checking if the databases were installed properly using `mantis check_sql`

```
mantis's latest release is: 1.5.5
```
```
Cython correctly compiled!
Checking extra files
Passed installation check on: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/Resources/essential_genes
Passed installation check on: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/Resources/NCBI/gc.prt.dmp
Passed installation check on: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/Resources/Taxonomy.db
Checking references installation
Failed installation check on [path unavailable]: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/NOG/
Passed installation check on: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/NCBI/
Passed installation check on: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/pfam/
Passed installation check on: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/kofam/
Failed installation check on [invalid referecence type]: /home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/tcdb/
Installation check failed on:
/home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/NOG/
/home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/References/tcdb/

------------------------------------------
--------INSTALLATION CHECK FAILED!--------
------------------------------------------
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/mantis/bin/mantis", line 11, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/mantis/__main__.py", line 218, in main
    check_installation(mantis_config=mantis_config, check_sql=True, no_taxonomy=no_taxonomy)
  File "/home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/mantis/assembler.py", line 27, in check_installation
    mantis.check_installation(check_sql=check_sql)
  File "/home/subudhak/miniconda3/envs/mantis/lib/python3.10/site-packages/mantis/assembler.py", line 628, in check_installation
    raise InstallationCheckNotPassed
mantis.exceptions.InstallationCheckNotPassed: Installation check not passed! Make sure you've setup the databases


```

**Comment by PedroMTQ** [comment]
Hello @Rohit-Satyam 
could you please share your config file?

Regards,
Pedro

**Comment by Rohit-Satyam** [comment]
Hi @PedroMTQ. It appears like some database failed to download previously (maybe due to internet issues). I reran the `mantis setup` command and now it works.
